### PR TITLE
Support for php82

### PR DESCRIPTION
**Pull request by wukis**

### CODE REVIEW

**Comment by wukis** [comment]
I'm not sure about lower-cases namespace for the container interface. phpcs complained, I simply ran phpcbf and that was the automated formatting.

**Comment by fabiang** [comment]
Thank you for your contribution.

PHPCS was wrong; therefore you should revert those changes and ignore the error. If this error comes when executing phpcs installed by composer in this project let me know and I'll fix it.

Secondly: are those updates of the dependencies really necessary?

**Comment by fabiang** [comment]
Also the unit tests weren't executed when you opened your PR, which should be fixed now. And last but not least I deleted the composer.lock. So please rebase your changes to the current develop branch, so we can see if the tests are successful under PHP 8.2. Thanks.

**Comment by wukis** [comment]
PHPCS complains about the container interface. It was installed with the project dependencies. I can roll it back, but the test part of phpcs will fail. Regarding the dependencies - as this will run within laminas context, I just wanted to align latest laminas dependencies with dependencies that would be pulled as "latest" at this point in time. As the version bump is only minor, there should not be any breaking changes by packages and it should be backwards compatible

**Comment by wukis** [comment]
I ran the composer test with 8.2.1 locally which was green with PR changes.

**Comment by fabiang** [comment]
Yeah since you just updated some require-dev's I guess were fine here, I was just curious. Just ignore the PHPCS error and I'll fix it after I've merged your PR.

**Comment by fabiang** [comment]
LGTM. I'm currently fixing the errors that are occurring in the GH actions.

**Comment by wukis** [comment]
If I understand this correctly, the use of ocular.phar with php 8.2 is not supported. Sorry, I'm not really familiar with scrutinizer.

**Comment by wukis** [comment]
This is what I get from phpcs


Screenshot 2023-01-19 at 22 04 15

**Comment by fabiang** [comment]
Merged this locally. ocular.phar triggers an error since PHP 8 and it looks like Scrutinizer is not going to fix it, but it's working anyway. And as said: just ignore the error from phpcs.

If you have a PHP 8.2 application available, I would kindly wait before drafting a new version, so you can test the changes.

Very appreciated.

**Comment by wukis** [comment]
Well the initial reason of doing this was the migration to PHP8.2. There is heavy usage of assetic and with the locked php version I can't. I will use the forked version to test it out.

**Comment by fabiang** [comment]
Released as v3.3.0

**Pull request closed without merging**
